name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout 
      uses: actions/checkout@master
    
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}