name: deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - 
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: S4nti1217
        password: D0cker.1217*
    
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
         push: true
         tags: ${{ github.sha }}

