on: push
name: deploy
jobs:
  deploy:
    name:  deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-actions@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       repository: s4nti1217/docker101tutorial
       tag_with_ref: true
       tag_with_sha: true
       tags: ${{ github.sha }}